;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        backward-sexp
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        comint-delchar-or-maybe-eof
        delete-indentation
        delete-pair
        dired-toggle-read-only
        eval-last-sexp
        fill-paragraph
        forward-sexp
        go-mode-insert-and-indent
        haskell-indentation-delete-backward-char
        indent-for-tab-command
        kill-region
        kill-sexp
        mark-sexp
        next-error
        nxml-electric-slash
        org-delete-char
        org-kill-line
        paredit-backward
        paredit-backward-kill-word
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-open-round
        query-replace
        sgml-slash
        wdired-finish-edit
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        python-indent-dedent-line-backspace
        ))
