(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-PDF-mode t)
 '(TeX-parse-self t)
 '(TeX-view-program-list (quote (("open" "open %o"))))
 '(TeX-view-program-selection (quote (((output-dvi style-pstricks) "dvips and gv") (output-dvi "xdvi") (output-pdf "open") (output-html "xdg-open"))))
 '(ac-delay 0.2)
 '(ac-modes (quote (emacs-lisp-mode lisp-mode lisp-interaction-mode slime-repl-mode c-mode cc-mode c++-mode java-mode malabar-mode clojure-mode clojurescript-mode scala-mode scheme-mode ocaml-mode tuareg-mode coq-mode haskell-mode agda-mode agda2-mode perl-mode cperl-mode python-mode ruby-mode lua-mode ecmascript-mode javascript-mode js-mode js2-mode php-mode css-mode makefile-mode sh-mode fortran-mode f90-mode ada-mode xml-mode sgml-mode ts-mode sclang-mode go-mode scss-mode less-css-mode)))
 '(ac-quick-help-delay 1)
 '(ac-use-menu-map t)
 '(ag-highlight-search t)
 '(blink-cursor-mode nil)
 '(browse-url-browser-function (quote browse-url-generic))
 '(c-basic-offset 4)
 '(c-default-style (quote ((c-mode . "k&r") (c++-mode . "k&r") (java-mode . "tachyon") (awk-mode . "awk"))))
 '(case-fold-search t)
 '(column-number-mode t)
 '(cscope-indexer-suffixes (quote ("*.[chly]" "*.[ch]xx" "*.[ch]pp" "*.cc" "*.hh" "*.java")))
 '(current-language-environment "UTF-8")
 '(custom-safe-themes (quote ("8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" "d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" default)))
 '(dired-omit-files "^\\..*$")
 '(eclimd-default-workspace "~/Documents/workspace")
 '(ede-project-directories (quote ("/Users/manu/programming/libcuckoo")))
 '(elpy-default-minor-modes (quote (eldoc-mode highlight-indentation-mode yas-minor-mode auto-complete-mode)))
 '(flycheck-check-syntax-automatically (quote (save mode-enabled)))
 '(flycheck-clang-standard-library "libc++")
 '(flycheck-flake8rc "~/.config/flake8")
 '(global-linum-mode t)
 '(global-undo-tree-mode t)
 '(grep-files-aliases (quote (("all" . "* .*") ("el" . "*.el") ("ch" . "*.[ch]") ("c" . "*.c *.h") ("cc" . "*.cc *.cxx *.cpp *.C *.CC *.c++ *.c *.h *.hpp") ("cchh" . "*.cc *.[ch]xx *.[ch]pp *.[CHh] *.CC *.HH *.[ch]++") ("hh" . "*.hxx *.hpp *.[Hh] *.HH *.h++") ("h" . "*.h") ("l" . "[Cc]hange[Ll]og*") ("m" . "[Mm]akefile*") ("tex" . "*.tex") ("texi" . "*.texi") ("asm" . "*.[sS]"))))
 '(haskell-font-lock-symbols (quote unicode))
 '(haskell-indentation-ifte-offset 4)
 '(haskell-indentation-layout-offset 4)
 '(haskell-indentation-left-offset 4)
 '(haskell-indentation-starter-offset 1)
 '(haskell-indentation-where-post-offset 4)
 '(haskell-indentation-where-pre-offset 4)
 '(haskell-mode-hook (quote (capitalized-words-mode imenu-add-menubar-index turn-on-haskell-doc turn-on-haskell-indent)))
 '(haskell-program-name "ghci")
 '(ido-default-buffer-method (quote selected-window))
 '(ido-enable-flex-matching t)
 '(ido-enable-last-directory-history nil)
 '(ido-everywhere t)
 '(ido-record-commands nil)
 '(ido-save-directory-list-file "~/.emacs.d/.ido.last")
 '(ido-show-dot-for-dired t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(js3-mode-show-parse-errors t)
 '(less-css-compile-at-save t)
 '(locale-coding-system (quote utf-8) t)
 '(magit-use-overlays nil)
 '(menu-bar-mode nil)
 '(ns-tool-bar-display-mode (quote both) t)
 '(ns-tool-bar-size-mode (quote regular) t)
 '(org-confirm-babel-evaluate nil)
 '(password-cache-expiry nil)
 '(scroll-bar-mode nil)
 '(scss-compile-at-save t)
 '(sentence-end-double-space nil)
 '(sql-mysql-login-params (quote (user server port password)))
 '(tab-width 4)
 '(term-buffer-maximum-size 100000)
 '(tool-bar-mode nil)
 '(tramp-auto-save-directory "\"/tmp\"")
 '(visual-line-mode nil t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

